### ISSUE TITLE
Infinite load 

### ISSUE THREAD

**Issue by mcianamea-gsegroup** [foex-open-source/fos-image-slider#4]
Hi,
We encounter errors with the plugin

- In a region display selector
After loading the page, the spinner keeps spinning and the first image is never displayed. 

- In a Tab container region
No image is displayed

Apex version: 22.1.5
Database version: Oracle 19c

We did not have these errors in Apex version 21.2 and Oracle 12c.

Thanks in advance

![img-slider](https://user-images.githubusercontent.com/114092130/191546931-94711d33-eff3-48aa-84b2-371af7b8f251.png)

**Comment by foex-open-source** [comment]
Thanks for reporting the issue, it's fixed with the just published v22.1

**Comment by mcianamea-gsegroup** [comment]
Thank you for your reply and for the correction in the new version. We will test this and give you feedback.
